### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [AnilFurkanOkcun/UWMediaPicker-Android#1]
hello...

Your project is amazing... I came across it and as a logo designer who also loves contributing to open source project, I decided to help create a LOGO for your project...

Currently working on some idea concepts that I feel you may like... I will update it here once I am done with the concepts so you can give me your feedback on any adjustment you may want...

I will appreciate your response...

Regards...

**Comment by AnilFurkanOkcun** [comment]
Hello,

I'm so sorry for answering late. Actually I never thought of a logo for this project but of course you can create a logo. I would be happy to use.

Best Regards.

**Comment by chimzycash** [comment]
Awesome... 
I am working on it, and would update it here for your feedback

**Comment by chimzycash** [comment]
Hello @AnilFurkanOkcun 
Here is my logo idea concept... you can share your feedback and the logo color of your choice.

![logo design_uv media picker_background_icon test 1](https://user-images.githubusercontent.com/37814297/52980810-441bb900-33dc-11e9-8093-522b8a9b68db.jpg)
![logo design_uv media picker_background_icon test 2](https://user-images.githubusercontent.com/37814297/52980811-44b44f80-33dc-11e9-8479-e92873994048.jpg)
![logo design_uv media picker_background_icon test 3](https://user-images.githubusercontent.com/37814297/52980812-44b44f80-33dc-11e9-98de-dc9c5c5a82ff.jpg)
![logo design_uv media picker_background_icon test 4](https://user-images.githubusercontent.com/37814297/52980813-44b44f80-33dc-11e9-8e3f-02a3348b47ac.jpg)
![logo design_uv media picker_idea concept_new](https://user-images.githubusercontent.com/37814297/52980814-454ce600-33dc-11e9-94b3-841701d987be.jpg)

**Comment by AnilFurkanOkcun** [comment]
@chimzycash Oh it looks unique and very cool. I really liked it. I am grateful for your professional work. Thank you.
About color, as you can see I use white(#FFF), black(#000 and #272727) and blue(#0192D2) for this project but I was thinking about changing blue one as #3981F9. I like blue :).
For logo, you can use white and blue like #3981F9(you don't have to use this one specifically) with whatever you want (black, gray etc.)
Thank you again for awesome work.

**Comment by chimzycash** [comment]
Ok... Thanks for your awesome feedback @AnilFurkanOkcun ... I will make the color adjustments

**Comment by chimzycash** [comment]
Hello @AnilFurkanOkcun 
Here is the updated design... 

Which of the color mix options do you prefer



![logo design_uv media picker_background_icon test 1](https://user-images.githubusercontent.com/37814297/53133393-48c6a580-3573-11e9-98cc-d6b5287d24bf.jpg)
![logo design_uv media picker_background_icon test 3](https://user-images.githubusercontent.com/37814297/53133394-48c6a580-3573-11e9-8c18-a625c95cef55.jpg)
![logo design_uv media picker_background_icon test 4](https://user-images.githubusercontent.com/37814297/53133396-495f3c00-3573-11e9-9585-8ec3192611f7.jpg)
![logo design_uv media picker_background_icon test 4b](https://user-images.githubusercontent.com/37814297/53133399-49f7d280-3573-11e9-9809-b151f5bbd899.jpg)

**Comment by AnilFurkanOkcun** [comment]
Hi @chimzycash these are very beatiful works. Thank you very much, i think I like the second row first column rounded square one. If you want you can PR. I really like these, thank you again.

**Comment by chimzycash** [comment]
Ok.. Thanks for your response... I will prepare all the files and get them ready for your use.

**Comment by AnilFurkanOkcun** [comment]
@chimzycash Can you provide svg files too? By the way, I gave you credit in the readme file.

**Comment by chimzycash** [comment]
Thanks... I appreciate

Would get all the vector files including SVG ready and send

**Comment by AnilFurkanOkcun** [comment]
Done. If you want you can send vector files to anilfurkanokcun@gmail.com.

**Comment by chimzycash** [comment]
Hi... Here is the Google Drive Link Containing the files including the vector files
https://drive.google.com/drive/folders/1sWVUtoxIhqqqd9IvTgIEtztH-PmXaTIn?usp=sharing

**Comment by chimzycash** [comment]
Hi @AnilFurkanOkcun  ... Here is the Google Drive Link for the Files including the Vector and SVG Files
https://drive.google.com/drive/folders/1sWVUtoxIhqqqd9IvTgIEtztH-PmXaTIn?usp=sharing

**Comment by AnilFurkanOkcun** [comment]
Thank you for everything @chimzycash
