### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by WenLonG12345** [AnilFurkanOkcun/UWMediaPicker-Android#13]
Hi, I found there is an error in your README.md

    <color name="colorUwMediaPickerDoneActive">#000000</color>
    <color name="colorUwMediaPickerDoneInactive">#B3B3B3</color>

supposedly be like this: 

	<color name="colorUwMediaPickerBtnTextDoneEnable">#0192D2</color>
	<color name="colorUwMediaPickerBtnTextDoneDisable">#B3B3B3</color>

Kindly revise the error. Thank you. 
Anyway, you did a great on this library and looking forward for the enhancement on activity callback and video size trimming & compressing function <3

**Comment by AnilFurkanOkcun** [comment]
@WenLonG12345 Thank you for kind feedback :) I fixed the error. And thank you for your kind words. I will work on video more since I got multiple request for it. And I am always open to criticism and suggestion. I'm sure everything can be done better so I can always improve the project.
