### ISSUE TITLE
 how to get call back on no media is selected after onBackPressed

### ISSUE THREAD

**Issue by inforaamitsolutions** [AnilFurkanOkcun/UWMediaPicker-Android#16]
i have an transparent activity which will be called on any screen where particular media is needed so when i show this screen i have a dialog says take picture or video or select from gallery , and on selecting gallery i open the UWMediaPicker , now here what i want to know if a user cancels the selection and presses back than how to get call back with nothing selected or something like that..... i hope you get the gist of it.

**Comment by shaheer20** [comment]
Have the same issue @AnilFurkanOkcun  please look into that

**Comment by shaheer20** [comment]
I have found a solution and it worked for me.
Download the library and add to your project all files will be editable
add  `resultCallback?.invoke(selectedMediaList)` in returnResult() function contains in UwMediaPickerDialogFragment.class

**Comment by AnilFurkanOkcun** [comment]
Thank you for your feedback @inforaamitsolutions and @shaheer20 . Added this feature at version 1.3.3. You can use `setCancelCallback`. Also sorry for the late answer.
