### ISSUE TITLE
How to pick both Image & Video

### ISSUE THREAD

**Issue by mansiJspaceo** [AnilFurkanOkcun/UWMediaPicker-Android#4]
Using this library How can we pick image & video both at same time

**Comment by AnilFurkanOkcun** [comment]
It's not possible right now but I will add this feature.

**Comment by mansiJspaceo** [comment]
Thank you.

give me some brief idea how to achieve it.. or any reference for that

**Comment by AnilFurkanOkcun** [comment]
Added this feature at version 1.2.0 you can try it. Always welcome your comments and requests. Thank you. @mansiJspaceo

**Comment by mansiJspaceo** [comment]
Thank you..

**Comment by mansiJspaceo** [comment]
@AnilFurkanOkcun  How can i get both in Same Array as String. i can Select Image & videos both but don't get in same Array. i have to take two different array for this

**Comment by AnilFurkanOkcun** [comment]
> @AnilFurkanOkcun How can i get both in Same Array as String. i can Select Image & videos both but don't get in same Array. i have to take two different array for this

I did this for the sake of simplicity. If I send the video and image paths in the same list, I may have to return an extra Boolean value to understand which path is the video and which path is the image. In this way would you prefer to get a custom model(which contains String and Boolean) instead of String? If so, I can try to add it.

**Comment by mansiJspaceo** [comment]
first application Crash while get Result in on ActivityResult,
Now
i get list by this way for both select path
  **val selectedImagePaths = data.getStringArrayExtra(UwMediaPicker.UwMediaPickerImagesArrayKey)
            val selectedVideoPaths = data.getStringArrayExtra(UwMediaPicker.UwMediaPickerVideosArrayKey)**

but for this i have to take to different array list but if i want to take one list for this how can i achieve that

**Comment by mansiJspaceo** [comment]
when i select both video & images. click on done button it's gives me
exception . application will be crash
how can we solve it.
