### ISSUE TITLE
App Crash after pick & Click on Done Button 

### ISSUE THREAD

**Issue by mansiJspaceo** [AnilFurkanOkcun/UWMediaPicker-Android#6]
Application Crash While Clcik on **Done** Button. Now get result in **onActivityResult** 
got this Exception 
 **java.util.ConcurrentModificationException**
**com.anilokcun.uwmediapicker.ui.activity.UwMediaPickerActivity$returnResult$1$1.invokeSuspend**

**Comment by AnilFurkanOkcun** [comment]
Can you give me more information to reproduce this error? Or sample project.

**Comment by mansiJspaceo** [comment]
When i Pick both Images & Video at that it occurs error. application Crash. 

this is way get result of picked item.

This is code  to Pick image & video 





> btnMultipleSelection.setOnClickListener {
>             UwMediaPicker
>                 .with(this)                        // Activity or Fragment
>                 .setRequestCode(PICK_IMAGE)                // Give request code, default is 0
>                 .setGalleryMode(UwMediaPicker.GalleryMode.ImageAndVideoGallery) // GalleryMode: ImageGallery or VideoGallery, default is ImageGallery
>                 .setGridColumnCount(3)                                  // Grid column count, default is 3
>                 .setMaxSelectableMediaCount(6)                         // Maximum selectable media count, default is null which means infinite
>                 .setLightStatusBar(true)                                // Is llight status bar enable, default is true
>                 .enableImageCompression(true)                // Is image compression enable, default is false
>                 .setCompressionMaxWidth(1280F)                // Compressed image's max width px, default is 1280
>                 .setCompressionMaxHeight(720F)                // Compressed image's max height px, default is 720
>                 .setCompressFormat(Bitmap.CompressFormat.JPEG)        // Compressed image's format, default is JPEG
>                 .setCompressionQuality(85)                // Image compression quality, default is 85
>                 .open()
>         }   }
> 
>    @RequiresApi(Build.VERSION_CODES.KITKAT)
>     override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
>         super.onActivityResult(requestCode, resultCode, data)
>         if (data != null && resultCode == Activity.RESULT_OK && requestCode == PICK_IMAGE) {
> 
>             val selectedImagePaths = data.getStringArrayExtra(UwMediaPicker.UwMediaPickerImagesArrayKey)
>             val selectedVideoPaths = data.getStringArrayExtra(UwMediaPicker.UwMediaPickerVideosArrayKey)
>             val intent = Intent(this, VideoMaskingActivity::class.java)
>             intent.putExtra("filePaths", selectedVideoPaths)
>             startActivity(intent)
>             Log.d("PickImageActivity", "${selectedImagePaths}${selectedVideoPaths}")
>         }
> 
>     }

**Comment by mansiJspaceo** [comment]
yes sure... i send you code which i facing issue

  private fun returnResult() {
        if (selectedMediaList.isEmpty()) {
            this@UwMediaPickerActivity.toastStringRes(R.string.uwmediapicker_toast_error_media_select_failed)
            setResult(0, Intent())
            finish()
            return
        }
        launch {
            val progressDialog = getProgressDialog().apply { show() }
            var hasErrorOccurred = false

            if (settings.imageCompressionEnabled) {
                withContext(Dispatchers.IO) {
                    // This is background thread.
                    val imageCompressor = ImageCompressor(
                        settings.compressionMaxWidth,
                        settings.compressionMaxHeight,
                        settings.compressFormat,
                        settings.compressionQuality,
                        settings.compressedFileDestinationPath
                    )





//                    for ((index, selectedMedia) in
selectedMediaList.withIndex()) {
//                        if (selectedMedia.mediaType == MediaType.IMAGE) {
//                            try {
//                                val compressedImageFile =
imageCompressor.compress(File(selectedMedia.mediaPath))
//                                selectedMediaList.removeAt(index)
//                                selectedMediaList.add(
//                                    index,
//                                    SelectedMediaModel(
//                                        compressedImageFile.absolutePath,
//                                        MediaType.IMAGE
//                                    )
//                                )
//                            } catch (e: Exception) {
//                                e.message.logError()
//                                hasErrorOccurred = true
//                            }
//                        }
//                    }
                }
            }
            // This is UI/Main thread
            progressDialog.dismiss()
            // If an error has occurred and some media can still be
selected; show toast message about it
            if (hasErrorOccurred) {

this@UwMediaPickerActivity.toastStringRes(R.string.uwmediapicker_toast_error_some_media_select_failed)
            }
            val imagesAndVideosPair =
                selectedMediaList.partition { it.mediaType == MediaType.IMAGE }
            val imagesArray = imagesAndVideosPair.first.map {
it.mediaPath }.toTypedArray()
            val videosArray = imagesAndVideosPair.second.map {
it.mediaPath }.toTypedArray()
            val resultIntent = Intent()
            resultIntent.putExtra(UwMediaPicker.UwMediaPickerImagesArrayKey,
imagesArray)
            resultIntent.putExtra(UwMediaPicker.UwMediaPickerVideosArrayKey,
videosArray)
            setResult(Activity.RESULT_OK, resultIntent)
            finish()
        }
    }


 in this i comment code at that place i am facing issue. please fix it
this code

**Comment by AnilFurkanOkcun** [comment]
I will look into it

**Comment by mansiJspaceo** [comment]
also one more thing why are you compress images & also save in pictures.

**Comment by mansiJspaceo** [comment]
if you fix issue please update

**Comment by AnilFurkanOkcun** [comment]
I couldn't reproduce this, if you have sample code please send me and let me try.
