### ISSUE TITLE
gallery won't display on android Q

### ISSUE THREAD

**Issue by hichemLink** [AnilFurkanOkcun/UWMediaPicker-Android#7]
i have launched your simple app in android 10.0 but gallery won't open perfectly, it look like in images below

![01](https://user-images.githubusercontent.com/41273103/78780246-333e5600-7996-11ea-9955-d37f2e09b574.jpg)
![02](https://user-images.githubusercontent.com/41273103/78780250-35a0b000-7996-11ea-8169-5996b41c1afc.jpg)

**Comment by AmniX** [comment]
Faced same.
add 
> android:requestLegacyExternalStorage="true"

Into your App manifest application tag then you are good to go.

**Comment by hichemLink** [comment]
> Faced same.
> add
> 
> > android:requestLegacyExternalStorage="true"
> 
> Into your App manifest application tag then you are good to go.

Think you
