### ISSUE TITLE
App crashes when compression is enabled

### ISSUE THREAD

**Issue by PabloBFMV** [AnilFurkanOkcun/UWMediaPicker-Android#8]
When compression is enabled with all the parameters set on default the app crashes and restarts after selecting 2 or more images, if I only select 1 images everything works fine. Am I doing something wrong?

Thanks in advance!

**Comment by AnilFurkanOkcun** [comment]
@PabloBFMV Hi, sorry for being late. I fixed this issue with version 1.2.2. You can try it :) and thank you for the feedback
